In [12]:
import os 
import numpy as np
# Function to rename multiple files 

  

In [10]:

i = 0
filapath = "img/Project/"
for file in os.listdir(filapath): 
    filename, file_extension = os.path.splitext(file)
    # rename() function will 
    # rename all the files 
    print(file)
    src = filapath + str(file)
    dst = filapath + str(i)+str(file_extension)
    print(src,dst)
    os.rename(src, dst) 
    i += 1

IMG_20190424_172512705.jpg
img/Project/IMG_20190424_172512705.jpg img/Project/0.jpg
IMG_20190424_172516198.jpg
img/Project/IMG_20190424_172516198.jpg img/Project/1.jpg
IMG_20190424_172516301.jpg
img/Project/IMG_20190424_172516301.jpg img/Project/2.jpg
IMG_20190424_172520691.jpg
img/Project/IMG_20190424_172520691.jpg img/Project/3.jpg
IMG_20190424_172528969.jpg
img/Project/IMG_20190424_172528969.jpg img/Project/4.jpg
IMG_20190424_172549406.jpg
img/Project/IMG_20190424_172549406.jpg img/Project/5.jpg
IMG_20190424_172555627.jpg
img/Project/IMG_20190424_172555627.jpg img/Project/6.jpg
IMG_20190424_172606274.jpg
img/Project/IMG_20190424_172606274.jpg img/Project/7.jpg
IMG_20190424_172616194.jpg
img/Project/IMG_20190424_172616194.jpg img/Project/8.jpg
IMG_20190424_172618950.jpg
img/Project/IMG_20190424_172618950.jpg img/Project/9.jpg
IMG_20190424_172624475.jpg
img/Project/IMG_20190424_172624475.jpg img/Project/10.jpg
IMG_20190424_172627496.jpg
img/Project/IMG_20190424_172627496.jpg img/Proje

In [37]:
import itertools

In [65]:
t= np.array(list(itertools.repeat([0,1,2], 19)))
print(t)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [68]:
x = np.zeros((1,19,19,2))
print(x)
x[:,:,:, 0] = t.T
print(x)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]
  

ValueError: could not broadcast input array from shape (3,19) into shape (1,19,19)

In [ ]:
def create_cordinate(batch, n_rows, n_cols):
    

In [73]:
m = range(19)

In [78]:
k = np.repeat([0,1,2], 3)

In [79]:
k

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [80]:
t = np.array([1,2])

In [81]:
t.shape

(2,)

In [82]:
np.swapaxes(t)

TypeError: swapaxes() missing 2 required positional arguments: 'axis1' and 'axis2'

In [ ]:
def 